# -*- coding: utf-8 -*-
"""SUMMATIVE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/107AlyLlkr90WYs_0RkVXuK0ufXTS7tIU
"""

# Import packages
import numpy as np
import netCDF4
import matplotlib.pyplot as plt
import xarray as xr
# import cartopy.crs as ccrs
# import cartopy.feature as cfeature
import seaborn as sns
import pandas as pd
from sklearn.linear_model import LinearRegression
plt.rcParams['figure.figsize']=(20.0,10.0)
import pandas as pd



#I uploade the data 
from google.colab import files
uploaded = files.upload()

data =pd.read_csv("mental-health-depression-disorder-data-QueryResult.csv")
print(data.shape)
data.head
data.describe()

Y=data.year 
# print(Y)

disorders = ['schizophrenia' ]
X = data[disorders]
# print(X)
# , 'bipolar_disorder', 'eating_disorders', 'anxiety_disorders', 'drug_use_disorders' , 'depression'

bipo=['bipolar_disorder']
A=data[bipo]
# print(A)

ea=['eating_disorders']
E=data[ea]

an=['anxiety_disorders']
F=data[an]

dr=['drug_use_disorders']
D=data[dr]

de=[ 'depression']
I=data[de]

#mean  of independant varaible and dependant variable 

mean_x =np.mean(X)
mean_y =np.mean(Y)
mean_A=np.mean(A)
mean_E=np.mean(E)
mean_F=np.mean(F)
mean_D=np.mean(D)
mean_I=np.mean(I)

n=len(X)

numer=0
denom=0

for i in range(n):

  # numer +=(X[i+1]-mean_x)*(Y[i] - mean_y)
  # denom +=(X[i+1]-mean_x)**2

  # b1= numer / denom 
  b0 = mean_y -(b1*mean_x)
  # print(b1 , b0)

y = b0 +b1 *X *A*E*F*D*I

plt.plot(X,Y , color="blue", label = "Evolution")
plt.scatter(X,Y , c='red',label ='Factore' )

plt.xlabel('HEALTH MENTAL FACTOR')
plt.ylabel('YEAR')
plt.legend()
plt.show()

#rsquare
ss_t =0
ss_r =0

for i in range (n-1):
  # y_perd = b0+b1 *X[i]
  ss_t += (Y[i] -mean_y)**2
  # ss_r += (Y[i]-y_perd)**2

  r2 = 1 -(ss_r/ss_t)
  print(r2)

#More impact heath
expected = 0.1*b1+b0
print(expected)





